apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g87zohq93-java-springboot 
  janus-idp.io/tekton: g87zohq93-java-springboot
  backstage.io/kubernetes-id: g87zohq93-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g87zohq93-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml